"""Render the YAML into SQL. Nothing here is written by hand in the workspace.

One policy per governed sensitivity value. Roles are branches inside one
function rather than separate policies, because two policies resolving to
different masks on the same column make the query fail rather than pick one.
"""
from __future__ import annotations

import pathlib
import sys

from . import config

HEADER = "-- generated by src/governance/generate.py - do not edit by hand\n"


def _member_of(groups: list[str], member_fn: str) -> str:
    return " OR ".join(f"{member_fn}('{group}')" for group in groups)


def _function(sensitivity: str, partial_groups: list[str], settings: dict, masks: dict) -> str:
    gov = f"{settings['catalog']}.{settings['gov_schema']}"
    name = f"{gov}.mask_{sensitivity}"

    if not partial_groups:
        return (
            f"CREATE OR REPLACE FUNCTION {name}(val VARIANT, shape STRING)\n"
            "RETURNS VARIANT\n"
            f"RETURN {masks['masked']}::VARIANT"
        )

    branches = []
    for shape, spec in masks["shapes"].items():
        expression = spec["partial"].replace("{col}", "val")
        branches.append(f"      WHEN '{shape}' THEN ({expression})::VARIANT")
    branches_sql = "\n".join(branches)

    return (
        f"CREATE OR REPLACE FUNCTION {name}(val VARIANT, shape STRING)\n"
        "RETURNS VARIANT\n"
        "RETURN CASE\n"
        f"  WHEN {_member_of(partial_groups, settings['member_fn'])} THEN\n"
        "    CASE shape\n"
        f"{branches_sql}\n"
        f"      ELSE {masks['masked']}::VARIANT\n"
        "    END\n"
        f"  ELSE {masks['masked']}::VARIANT\n"
        "END"
    )


def _policy(sensitivity: str, exempt: list[str], settings: dict) -> str:
    scope = f"{settings['catalog']}.{settings['schema']}"
    gov = f"{settings['catalog']}.{settings['gov_schema']}"
    except_clause = ""
    if exempt:
        principals = ", ".join(f"`{group}`" for group in exempt)
        except_clause = f" EXCEPT {principals}"
    return (
        f"CREATE OR REPLACE POLICY mask_{sensitivity}\n"
        f"ON SCHEMA {scope}\n"
        f"COLUMN MASK {gov}.mask_{sensitivity}\n"
        f"TO `account users`{except_clause}\n"
        "FOR TABLES\n"
        f"MATCH COLUMNS has_tag_value('sensitivity', '{sensitivity}') AS c\n"
        "ON COLUMN c\n"
        "USING COLUMNS (get_column_tag_value(c, 'mask_shape'))"
    )


def _gate(exempt: list[str], settings: dict) -> str:
    scope = f"{settings['catalog']}.{settings['schema']}"
    gov = f"{settings['catalog']}.{settings['gov_schema']}"
    principals = ", ".join(f"`{group}`" for group in exempt)
    except_clause = f" EXCEPT {principals}" if exempt else ""
    return (
        f"CREATE OR REPLACE FUNCTION {gov}.block_all() RETURNS BOOLEAN RETURN FALSE\n;\n"
        "CREATE OR REPLACE POLICY block_unverified\n"
        f"ON SCHEMA {scope}\n"
        f"ROW FILTER {gov}.block_all\n"
        f"TO `account users`{except_clause}\n"
        "FOR TABLES\n"
        "WHEN has_tag_value('classification', 'unverified')"
    )


def render() -> dict[str, str]:
    settings = config.settings()
    matrix = config.matrix()
    masks = config.masks()
    roles = matrix["roles"]
    exempt_always = list(matrix.get("exempt", []))

    functions, policies = [], []
    for sensitivity in matrix["default"]:
        partial_groups = [r["group"] for r in roles.values() if r.get(sensitivity) == "partial"]
        clear_groups = [r["group"] for r in roles.values() if r.get(sensitivity) == "clear"]
        functions.append(_function(sensitivity, partial_groups, settings, masks))
        policies.append(_policy(sensitivity, clear_groups + exempt_always, settings))

    return {
        "010_functions.sql": HEADER + "\n;\n".join(functions),
        "020_policies.sql": HEADER + "\n;\n".join(policies),
        "030_gate.sql": HEADER + _gate(exempt_always, settings),
    }


def main() -> int:
    out = pathlib.Path(config.ROOT / "build")
    out.mkdir(exist_ok=True)
    for name, sql in render().items():
        (out / name).write_text(sql + "\n")
        print(f"wrote build/{name}  ({len(sql.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
